apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-blank-html-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "fluxpoc.daglab.dev"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: k8s-blank-html
            port:
              number: 443
